package fr.univ_lyon1.info.m1.stopcovid_simulator.model.remote;

import fr.univ_lyon1.info.m1.stopcovid_simulator.data.DatedKey;
import fr.univ_lyon1.info.m1.stopcovid_simulator.util.Observable;

import java.util.List;

public interface UserApi {

    /**
     * Set the model this API will interact with.
     * @param model
     */
    void setModel(ServerModel model);

    /**
     * Declare a user as infected.
     * @param userToken the user's token
     * @param covidToken the unique authorization token
     * @param keys the list of keys generated by the user
     */
    void declareInfected(String userToken,
                         String covidToken,
                         List<DatedKey> keys);

    /**
     * Get the list of known infected keys.
     * @return
     */
    List<String> getInfectedKeys();

    /**
     * Register a user on the server.
     * @return a unique user token.
     */
    String register();

    /**
     * Get the observable notifying when the infected key list gets updated.
     * @return
     */
    Observable getInfectedKeysUpdatedObservable();
}
